### ISSUE TITLE
Does the migrator works for V1 -> Docker Trusted registry 1.2.0

### ISSUE THREAD

**Issue by natarajanv** [docker/migrator#19]
The tool complains that [ERROR] v2 registry (http://r10a-docker7c.mitre.org) is not available

**Comment by mbentley** [comment]
It looks like you're providing the full URL as your `V2_REGISTRY_URL=` environment variable (e.g. - `http://r10a-docker7c.mitre.org` instead of `r10a-docker7c.mitre.org` when running the tool.  Migrator is expecting the URL to be utilizing HTTPS so `https://` automatically gets added.

**Comment by natarajanv** [comment]
Thanks, that was the issue.
