### ISSUE TITLE
Migrate from V1 to V2 with S3 storage without copying images

### ISSUE THREAD

**Issue by tremolo** [docker/migrator#33]
Is it possible to migrate from V1 registry (V0.9.1) to the new V2 registry without pushing and pulling all images? I know that this is not the normal migration path, but for what reason do the image need to get pulled? We have a lot of images in our private registry and it would be great not to generate too much traffic if there is no good reason. Would it be possible to convert existing meta-data only ?

**Comment by mbentley** [comment]
Sorry, I thought that I had replied to this at some point before.  Unfortunately it is not possible as far as I am aware of.  If it was, it would require a great deal of engineering to be able to re-order all of the data as well as re-create all of the manifests without ending up with potentially broken images.
