### ISSUE TITLE
problem to push images in registry v2

### ISSUE THREAD

**Issue by tonton1728** [docker/migrator#38]
Hi,
I'm trying to migrate my images from a v1 registry to a v2 registry. To do so, I use a reverse proxy to add SSL but I'm not using authentication.
I've got no problem to pull images from registry v1 but when I push I've got this error : 
```
[OK] Verified v2 registry (registry.si3si.com) is available
[!!] Please login to registry.si3si.com:
Username:
FATA[0001] Error response from daemon: no successful auth challenge for https://registry.si3si.com/v2/ - errors: []
``` 
I also tried to add NO_LOGIN=true env variable but in this case I've got another error : 
```
cat: /root/.dockercfg: No such file or directory

[ERROR] Non-zero exit code
[ERROR] Migration from v1 to v2 failed!
```

I've got no other idea of what I can tried

If you need any other information, do not hesitate

Gilles DEHAUDT

**Comment by mbentley** [comment]
I think I see the issue.  It is still trying to decode user credentials even if `NO_LOGIN` is set to `true`.  PR incoming to fix.

**Comment by mbentley** [comment]
Please test when you are able and let me know if this solves the problem for you.

**Comment by tonton1728** [comment]
I've just tested it and it works fine
Thanks for your quick reaction
