### ISSUE TITLE
Custom CA's

### ISSUE THREAD

**Issue by clemenko** [docker/migrator#42]
How do I add custom CA's into the tool?

**Comment by mbentley** [comment]
One method would be to have your custom root CA to your engine that you are using to perform the migration on and set the `USE_INSECURE_CURL` environment variable appropriately.  If you don't want to set the `USE_INSECURE_CURL` environment variable, you could create a Dockerfile that adds your root CA's public certificate to the existing trusted root CAs.  Here is an example:

```
FROM docker/migrator:latest

COPY your_root_ca.crt /usr/local/share/ca-certificates/your_root_ca.crt
RUN update-ca-certificates
```

Either way, your root CA certificate needs to be added to wherever your engine is running (you can use the same method above if you are on Ubuntu or Debian) and then you need to restart that engine for it to recognize the changes.

**Comment by clemenko** [comment]
I would prefer the insecure method as I have access to localhost:5000 on the v2 server. But I might need to add the CA so I can hit the  v1 server.  THanks for the help.

**Comment by mbentley** [comment]
Just to make sure it is clear, the insecure method does still require SSL certs.  I could probably add flags to allow connections over `http` instead of `https` but in all honesty, I'd rather encourage people to make sure they are securing their registries with SSL.

**Comment by clemenko** [comment]
Is there any way to use http only? Like I said I want to run this on the v2 host where I have access to local host:5000.

**Comment by clemenko** [comment]
USE_INSECURE_CURL  worked thanks.
