### ISSUE TITLE
Migrating from library namespace does not work

### ISSUE THREAD

**Issue by natarajanv** [docker/migrator#44]
Migrating from any workspace other than "library" name space works fine. For some reason it drops the library namespace:

[INFO] Retagging all images from 'dockerdev1.mitre.org' to 'dockeradm1.mitre.org'
[OK] dockerdev1.mitre.org/alpine:2.0 > dockeradm1.mitre.org/alpine:2.0
[OK] dockerdev1.mitre.org/alpine:2015-02-27 > dockeradm1.mitre.org/alpine:2015-02-27
[OK] Successfully retagged all images

my alpine image is stored as dockerdev1.mitre.org/library/alpine

**Comment by mbentley** [comment]
Sorry for the delay in a response.  This was originally the intent as if someone had images without a namespace, such as in the example of official images on Docker Hub but done on a private repository, it would trim that as the API would return it as actually being in the namespace library.  With how namespaces should be handled based on what I understand (e.g. - there should always be a namespace no matter what), it now makes sense to remove the trimming of the `library` namespace.  I'll see if I can update this shortly.

**Comment by mbentley** [comment]
#47 has been merged.  Could you let me know if this solves the issue?  Thanks!

**Comment by natarajanv** [comment]
Thanks @mbentley . I was able to migrate images from library namespace. I will close this issue.
