### ISSUE TITLE
Missing MAINTAINERS file

### ISSUE THREAD

**Issue by thaJeztah** [docker/migrator#45]
I'm working on preparing the open source repositories for the new centralized maintainers file, but noticed this repository does not yet have a MAINTAINERS file.

I can create a PR to fix this, but I'm not sure who should be included as maintainer(s).

@mbentley are you the only maintainer, or should I add other people here?

for reference, see docker/opensource#35 and docker/docker#18321

**Comment by mbentley** [comment]
Yes, I'm currently the only maintainer.

**Comment by thaJeztah** [comment]
Cool! I'll ping you when I create the PR, thanks!
