### ISSUE TITLE
Doesn't work with client certificates

### ISSUE THREAD

**Issue by lorenz** [docker/migrator#48]
When both registries use client certificates the migrator doesn't work, it fails with `curl => API failure` because curl doesn't use Dockers client certificates.

**Comment by mbentley** [comment]
Just to make sure I am fully understanding the root cause of the issue, do you mean when using self signed certificates where you place your cert or CA cert in `/etc/docker/certs.d/<registry-fqdn>/ca.crt`?

**Comment by lorenz** [comment]
No, the certificates are signed by a public CA. I mean the client certificates placed in `/etc/docker/certs.d/client.{pem,key}`.

**Comment by mbentley** [comment]
Ah ok, thanks for the clarification.  I'll see if I can add in some detection of client certificates via allowing users to provide `/etc/docker/certs.d/` as a volume and utilizing them for the curl commands.

**Comment by lorenz** [comment]
Are you working on this or should I do it? I looked through the code and it doesn't look too difficult.

**Comment by mbentley** [comment]
If you're willing to give it a try, that would be awesome and greatly appreciated!
