### ISSUE TITLE
[ERROR] curl => API failure Migration from v1 to v2 failed!

### ISSUE THREAD

**Issue by kforner** [docker/migrator#59]
Hello,
I'm trying to migrate from a 0.9.0 registry running in a docker, bound on port 5000, to a registry v2 running in a docker on port 5001.

I tried:
```
docker run -it \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-e V1_REGISTRY="localhost:5000" \
	-e V2_REGISTRY="localhost:5001" \
	-e USE_HTTP=true \
	docker/migrator
[!!] Please login to localhost:5000:
Username: 
WARNING: login credentials saved in /root/.dockercfg.
Account created. Please see the documentation of the registry http://localhost:5000/v1/ for instructions how to activate it.

[INFO] Getting a list of images from localhost:5000

[ERROR] curl => API failure
[ERROR] Migration from v1 to v2 failed!
```

I also tried using NO_LOGIN=true with the same result.

What can I do ?

**Comment by mbentley** [comment]
@kforner - Using localhost will not work in this case because localhost from the standpoint of the migrator script while running is actually the container itself that you're running migrator from.  You would need to specify the IP address or hostname of your actual server for it to be able to communicate.

**Comment by kforner** [comment]
@mbentley thanks a lot for this instant reply. 
Using the IP address improves the situation, but now I get:
```
docker run -it \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-e V1_REGISTRY="10.9.70.3:5000" \
	-e V2_REGISTRY="10.9.70.3:5001" \
	-e NO_LOGIN=true \
	-e USE_HTTP=true \
	docker/migrator
INFO] Getting a list of images from 10.9.70.3:5000
[OK] Successfully retrieved list of Docker images from 10.9.70.3:5000

[INFO] Full list of images from 10.9.70.3:5000 to be migrated:
...
[OK] End full list of images from 10.9.70.3:5000

[!!] Press any key to begin migration process [ctrl+c to abort]

[INFO] Pulling all images from 10.9.70.3:5000 to your local system
[INFO] Pulling 10.9.70.3:5000/library/qbrocker311:latest
FATA[0004] Error response from daemon: invalid registry endpoint https://10.9.70.3:5000/v0/: unable to ping registry endpoint https://10.9.70.3:5000/v0/
v2 ping attempt failed with error: Get https://10.9.70.3:5000/v2/: EOF
 v1 ping attempt failed with error: Get https://10.9.70.3:5000/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.9.70.3:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.9.70.3:5000/ca.crt 
[ERROR] Failed to pull 10.9.70.3:5000/library/qbrocker311:latest
```

**Comment by mbentley** [comment]
Could you verify which version of the docker engine you're running on your host you're running the migration from?

**Comment by kforner** [comment]
sure
``` 
>docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by mbentley** [comment]
OK, that should work (would have to verify) but to just test basic pulling, are you able to pull the image directly from your host using `docker pull 10.9.70.3:5000/library/qbrocker311:latest` or `10.9.70.3:5000/qbrocker311:latest`?  I'm guessing it will end up with the same error.

Since `localhost` is trusted automatically since it is expected that localhost is always going to be the actual local machine, it doesn't need the `--insecure-registry` flag on the daemon.  This is used when you have a registry that does not have SSL/TLS which is what it sounds like is the case since you have `USE_HTTP=true` (https://docs.docker.com/registry/insecure/).

**Comment by kforner** [comment]
Good guess:
```
docker pull 10.9.70.3:5000/library/qbrocker311:latest
Error response from daemon: invalid registry endpoint 
```
I have a TLS and authentication layer using an apache proxy server on top of my registry.
So what should I do ? 

Thanks.

**Comment by mbentley** [comment]
So is your Apache reverse proxy running on port 5000?  If you're able to pull the images from your engine, I would specify the Apache reverse proxy's address as the `V1_REGISTRY` instead of directly to the v1 and include your authentication as well.

**Comment by kforner** [comment]
> So is your Apache reverse proxy running on port 5000?

no the registry with no authentication runs on port 5000, the apache proxy redirects queries from port https/443 to 5000.

> I would specify the Apache reverse proxy's address as the V1_REGISTRY instead of directly to the v1 and include your authentication as well.

It works !
Using 
```
docker run -it \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-e V1_REGISTRY="docker.xxxx.com" \
	-e V2_REGISTRY="10.9.70.3:5001" \
	docker/migrator
```
Naively, I was thinking than to avoid authentication/https it was simpler to use the bare registries. 

As a side-question, where are the temp images stored ? 

Thanks a lot for your help Matt !!

**Comment by mbentley** [comment]
No problem!  The images are stored locally on your Docker Engine that you're running migrator from.  It has the docker binary in the container to use as the docker client and uses your local engine as your server via `/var/run/docker.sock`.  So the images are stored on your local system and are removed at the end of the migration process to return the used disk space.
