### ISSUE TITLE
[ERROR] v2 registry  is not available

### ISSUE THREAD

**Issue by kforner** [docker/migrator#62]
Hi again,

In fact it's not working. It fails at the push step.
I used:
```
docker run -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e V1_REGISTRY="my.old.registry" \
    -e V2_REGISTRY="10.x.x.x:5001" \
    -e USE_HTTP=true \
    docker/migrator
```
It fails with:
```
[ERROR] v2 registry (10.x.x.x:5001) is not available
[!!] Verify v2 registry is functioning as expected; press any key to continue to retry [ctrl+c to abort]
```
From what you explained to me, I think I understand what's going on, but I do not know how to work  around it using migrator:
 I cannot use localhost:5001 as my V2_REGISTRY since it is executed in the docker container in which localhost is a different computer. That's why I used either the IP address or different DNS names. But it is only localhost that is trusted by default by the docker/registry:2

I guess I could finish the pull manually by executing a push loop on the host using localhost, but is there any way to make it work via the migrator ?

Thanks

**Comment by mbentley** [comment]
So if you want to try just running it natively, you can give that a shot by just directly running the migrator.sh script while specifying the environment variables necessary.  You'll just need to make sure you have `wget` and `jq` installed and it should then work with `localhost`.

**Comment by kforner** [comment]
I changed my strategy, and configured a proxy for the v2 too. It's currently pushing. 
thanks.

**Comment by FelikZ** [comment]
For me it does not work. It pulls all the images from v1 repo, tag them correctly but said the same error:

```
[ERROR] v2 registry (localhost:5000) is not available
[!!] Verify v2 registry is functioning as expected; press any key to continue to retry [ctrl+c to abort]
```
And yes I have verified, v2 registry works.

So I have to push images manually:
```bash
docker images --format '{{.Repository}}' | grep localhost | sort -u | xargs -L 1 docker push
```

Hope this will help somebody.

**Comment by mbentley** [comment]
Right, localhost will never work because localhost is the container itself, not your current docker engine.  You have to think about it from the container perspective.
