### ISSUE TITLE
If search module is not enabled the migrator doesn't work

### ISSUE THREAD

**Issue by ZJaffee** [docker/migrator#65]
https://github.com/docker/docker/issues/10906
https://github.com/docker/docker-registry#search-engine-options

If you don't have search enabled the migrator script will return an empty list of images as the list of images you have to migrate over to the new repo.

**Comment by mbentley** [comment]
If there is no search endpoint, there isn't a way to find out what is in the registry.  Do you have some other method of which you're able to find out what is in your registry?

**Comment by ZJaffee** [comment]
I should have specified earlier, but I am able to get all the repo data from S3, so I can wrangle that data down so that I have just the repo names and their tag names.

**Comment by mbentley** [comment]
So it sounds like you'd like to be able to feed in a list of images as the source and be able to migrate from that, correct?  That should be pretty easy to implement.

**Comment by ZJaffee** [comment]
Basically, I'm currently just hacking something together, but it's not clean enough where I'd want to make a PR. I mostly just filed the issue to see if there were any quick work arounds before I continued that.

**Comment by mbentley** [comment]
Ah ok.  Gotcha.  If you can't start another container with the search endpoint enabled, doing something were you bypass the getting of the list and manually getting it inserted would certainly be the quickest.

**Comment by ZJaffee** [comment]
Cool, also with the in the current implementation of the migrator, is it the case that I want that list to look like:

```
library1/image1:latest
library1/image2:latest
library2/image1:5.0
```
Or is the format different.

**Comment by mbentley** [comment]
Yup, what it comes down to is bypassing the `query_source_images` function which builds the list which si put into the environment variable `FULL_IMAGE_LIST`.  This should be a list of your images and `V1_REGISTRY` just needs to be set to your FQDN and it should work.  I.E. - `FULL_IMAGE_LIST="library1/image1:latest library1/image2:latest library2/image1:5.0"`
