### ISSUE TITLE
Will this script work with v2 and token based authentication?

### ISSUE THREAD

**Issue by wolfch** [docker/migrator#70]
We used migrator script to migrate from v1 to a v2 registry which was setup without any authentication/authorization.  This worked great, thanks!

Now we have a v2 registry setup with both token-based authentication along with authorization, i.e. using teams and authorized namespaces (public/private) via the Portus project:
https://github.com/SUSE/Portus/

I'm thinking that even if the migrator script can authenticate, I can't see how it would handle authorizations.  Any thoughts?

**Comment by mbentley** [comment]
@wolfch - My apologies for the late reply here.  There isn't much in the way of handing other namespaces in the destination registry.  The current expected workflow for migration is that in your destination registry, you would have all namespaces pre-created with the appropriate permissions.  The user that is performing the migration is expected to be an administrator which would grant them access to push to any namespace.  It's not exactly ideal but with the possibility of having many different destination registries, maintaining how exactly their APIs work to create those automatically would be a quite a task.

**Comment by wolfch** [comment]
@mbentley - No worries, pre-creating the namespaces is what we did.  This is ok for a small team but won't scale to when there hundreds of users/namespaces.  I will inquire with the Portus devs to see if they plan on exposing a web API.  thanks.
