### ISSUE TITLE
migrate from DTR 1.4.3 to DTR 2.0

### ISSUE THREAD

**Issue by natarajanv** [docker/migrator#78]
Hello,
   I used the migrator to migrate from registry V1 to DTR 1.4.3, but now we are planning on upgrading to DTR 2.0, and there is no path to migrate the images. is it possible to support V2 to V2 migration?

Thanks

**Comment by mbentley** [comment]
For the most part, v2 to v2 migration isn't necessary.  For DTR, there is a migrate command (see https://docs.docker.com/docker-trusted-registry/install/upgrade/upgrade-major/).  The backend storage needs to be remounted to the installation or copied over as the backend registry is still the distribution project and the format of that hasn't changed.
