### ISSUE TITLE
Ability to start from a certain image

### ISSUE THREAD

**Issue by TanmayaA** [docker/migrator#88]
When moving thousands of images, you don't always want to retry from start. Is it possible to add this feature?

**Comment by jdnurmi** [comment]
Same want, and it would be nice to be able to 'shard' as well - when doing what is effectively S3->disk->S3 transfers, being bound by serial disk IO hurts a lot.

**Comment by mbentley** [comment]
My apologies for the lack of a reply; this is something I'm interested in adding when I have the time unless someone else gets to it first.

**Comment by madmuffin1** [comment]
since #97 and more enhanced in #111 you can tell the process to query the target for existing tags and skip them.

**Comment by TanmayaA** [comment]
Look great. Thanks! 👍
