### ISSUE TITLE
Namespaces returns owners only, not read access

### ISSUE THREAD

**Issue by Brett55** [docker/migrator#93]
When doing a GET on https://hub.docker.com/v2/repositories/namespaces 
it returns only namespaces in which members are owners, rather than read access. Thus causing this code block to raise an exception incorrectly

https://github.com/docker/migrator/blob/master/migrator.sh#L430-L436

**Comment by mbentley** [comment]
Ah crap, you're right.  I'll have to see what API I might have access to to check what organizations a user has any access to.  In the meantime, I'll put in a PR to bypass the check as you're definitely right.

**Comment by Brett55** [comment]
Thanks for quick response!

**Comment by mbentley** [comment]
Apparently this should return what orgs a user belongs to: https://hub.docker.com/v2/user/orgs/

**Comment by mbentley** [comment]
Looks like this will fix it...change https://github.com/docker/migrator/blob/master/migrator.sh#L431 to:
`NAMESPACES=$(curl -sf -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/user/orgs/ | jq -r '.results|.[].orgname') || catch_error "curl => API failure"`

**Comment by Brett55** [comment]
@mbentley looks good, thanks for quick fix
